env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
# suppresses warnings for unused function variables
  no-unused-vars: ["error", { "args": "none" }]